env:
  global:
    - CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID

language: go
go:
  - 1.10.x
dist: trusty
sudo: false

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -v github.com/codeclimate/test-reporter
install:
  - $GOPATH/bin/dep ensure
before_script:
  - test-reporter before-build
script:
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test -coverprofile c.out ./...
after_script:
  - test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
